title: Recdb-postgresql
description: RecDB is a recommendation engine built entirely inside PostgreSQL 9.2
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
